### ISSUE TITLE
Move pre-commit hook to pre-push

### ISSUE THREAD

**Issue by flut1** [mediamonks/seng-boilerplate#18]
Our pre-commit hook checks if you have any linting errors and/or unit test failures. However, this makes it really impractical to make small incremental commits when working on a feature.
If we move these checks to pre-push we still have the guarantee that origin is without linting errors and failing tests, while making it more practical to do small local commits.

**Comment by ThaNarie** [comment]
- [ ] Find a replacement for [pre-commit](https://github.com/observing/pre-commit)

**Comment by mientjan** [comment]
completele agree its almost impossible to do updates to your code because every change needs to be complient
