### ISSUE TITLE
Create separate entry points for different builds

### ISSUE THREAD

**Issue by flut1** [mediamonks/seng-boilerplate#29]
We can distinguish two different build types:
- Builds that output a single file. This is the case for our amd/umd/system js files.
- Builds that output a file per module. This is the case for the es6 build and the output to the 'lib' folder for npm. 

We now have a single typescript entry point when building our source files, namely `src/index.ts`. However, we cannot have a single entry point that is optimized for both of the build types described above. Some example differences between the builds:

 - We would want to include the `ts-helpers` module in our single-file output and add the `noEmitHelpers` flag in the typescript compiler because this will make our bundle size smaller. It is however not possible to use this flag in our lib/es6 output, because we need the guarantee that the helpers are included on every imported module. 
 - In the single file builds, we want to export modules that are not a dependency of the default exports so they are still reachable from the outside. This does not make sense in the other builds, because these modules are already exported as a separate file.

How would we name these entry files to prevent any confusion?

**Comment by ThaNarie** [comment]
As an addition, builds that output a file per module (`typescript-npm` and `typescript-es6`) have a difference on it's own.

The current index.ts acts as a entry point for easy convenience. `import ... from "seng-module"`, where default and named exports can be accessed. Other files not referenced from this main file need to be imported from `"seng-module/lib/..."`.
As this affects the bundle size when this module is used in another project, we don't want to reference too much files in there; as a rule of thumb we should only add files that are imported in general use cases of the module, and/or files that are internally referenced by the default export class itself (as that doesn't influence the bundle size).

Other files (that can be used standalone, or are optional plugins for the main file) are not referenced by the `index.ts`, and are currently not compiled and moved to the output folder. (There is no Dummy.js in the output folders.)
The only other option besides referencing them in the `index.ts` (what we do not want) is to include them in the `"files"` section of the `tsconfig.json`.
With TypeScript 1.x this should be done per-file, but in TypeScript 2.0 they finally introduced globbing in the `"include"` section of the `tsconfig.json`.

It looks like for those cases, using that method is the only option.

And I think that the systemjs target built with `tsc` can use the same 'main' file as the other targets being built with webpack.

So to conclude, I think we end up with 3 methods:
* `index.ts` for `npm` and `es6` targets (for default export and convenience named exports)
* `"files"` or `"include"` to also compile and move other files
* `lib.ts` (or other name) as an entry for single-file-output libs (used by webpack and typescript-system`)
