### ISSUE TITLE
Add typings as build dependency in README.md

### ISSUE THREAD

**Issue by gacosta89** [mediamonks/seng-boilerplate#37]
When I did 'npm install' I got the following message
    
    > seng-boilerplate@1.2.0 postinstall D:\workspace\seng-boilerplate
    > npm run typings
    
    
    > seng-boilerplate@1.2.0 typings D:\workspace\seng-boilerplate
    > typings install

    'typings' is not recognized as an internal or external command,
    operable program or batch file.

I didn't find it as a dependency and according to [typings](https://github.com/typings/typings) docs is meant to be installed globally. So if that is the case you should specify it in README.md.

**Comment by ThaNarie** [comment]
You're right, thanks for the suggestion!

**Comment by gacosta89** [comment]
:) if you want i can do a PR

**Comment by ThaNarie** [comment]
I want :)
