### ISSUE TITLE
Deployment stalls because of bad github credentials

### ISSUE THREAD

**Issue by jesse-mm** [mediamonks/seng-boilerplate#54]
Currently travis fails on deployment to github.

**Comment by ThaNarie** [comment]
@jesse-mm This is something you could fix yourself:
https://github.com/mediamonks/seng-boilerplate/wiki/Travis#github-release

**Comment by jesse-mm** [comment]
Updated github release token reference 8ec0cef9d89c1895a2419211862f9bdfdc4a1d63
